<a href="https://colab.research.google.com/github/khushboo-gehi/Py-ML-DL/blob/main/_DSPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
first_numpy_array = np.array([1,2,3,4])

In [ ]:
print(first_numpy_array)

[1 2 3 4]


In [ ]:
array_zero = np.zeros((3,3))
array_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
array_ones= np.ones((3,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
array_empty = np.empty((2,3))
array_empty

array([[4.65319068e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
np_arange = np.arange(12)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np_linspace = np.linspace(1,6,5)

In [ ]:
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [ ]:
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
twoD_arr = oneD_array.reshape(3,5)
print(twoD_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


SciPy - Eigenvalues and Eigenvector

In [ ]:
import numpy as np
from scipy import linalg

In [ ]:
test_rating_data = np.array([[5,8],[7,9]])
eigenValues, eigenVector = linalg.eig(test_rating_data)
first_eigen, second_eigen = eigenValues

In [ ]:
print(first_eigen, second_eigen)

(-0.745966692414834+0j) (14.745966692414834+0j)


In [ ]:
print(eigenVector[:,0])

[-0.81220939  0.58336601]


SciPy - CDF and PDF

In [ ]:
from scipy.stats import norm

In [ ]:
norm.rvs(loc=0,scale=1,size=20)

array([ 0.18249472,  0.69211549,  1.73369665,  1.2255157 , -0.12461409,
        0.53318407, -0.27228951, -0.37805469,  0.31656412, -1.67636122,
        1.79290386, -1.75608292, -2.00444522, -0.57583368,  0.85736823,
        1.06248742, -0.48693221, -1.12235968,  0.76599755, -0.3878299 ])

In [ ]:
#Cumulative Distribution Function
norm.cdf(10, loc=1,scale=3)

0.9986501019683699

In [ ]:
#Probability Density Function
norm.pdf(14,loc=1,scale=1)

7.998827757006813e-38

Web Scraping - Navigating the Tree

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
book_html_doc = ""